### ISSUE TITLE
On tiny resolutions some admin tabs aren't shown

### ISSUE THREAD

**Issue by djensenius** [condomanagement/condo-web#81]
...or they are non obvious to see. 

@MaggieShan can you investigate?

**Comment by MaggieShan** [comment]
I've tested the website on various screen resolutions and it seems like screens with narrow widths will have the Reservations tab cut out (specifically the letters n,s), in very specific width sizes (from 1049px to 996px) the Reservations tab is completely cut out.  I also agree that the tabs are quite small on mobile screens.

For a quick fix solution, we can:
* Increase tab/font size on mobile sizes 
* Change the tabs to be scrollable, so when one is cut out, it will be indicated and still reachable through scroll arrows 

General/long-term solutions include: 
* Turning tabs and nav bar into columns for easier access (since the entire website is quite small on mobile)

**Comment by djensenius** [comment]
How about implementing the scrollable tabs? Do you think that would help?

https://material-ui.com/components/tabs/

**Comment by djensenius** [comment]
You suggested that. 😂

Yeah let's go that way!
